### ISSUE TITLE
www --up . is failing

### ISSUE THREAD

**Issue by iatenothingbutriceforthreedays** [tycobbb/www#1]
`www .` works but `www --up .` doesn't, it looks like for some reason it's trying to delete files that don't exist because they weren't built because they're in `.gitignore`:
```
* copy  - README.md
* copy  - documentation
* copy  - documentation/21-10-2022
* copy  - documentation/21-10-2022/mario-lylat-system.MOV
* copy  - documentation/21-10-2022/mario-flicker.MOV
* copy  - documentation/21-10-2022/killer-instinct-matte.MOV
* copy  - documentation/21-10-2022/checkers.jpg
✔ listening on localhost:8888
- delete: .git/index.lock
- delete: dist/documentation
- delete: dist/README.md
- delete: dist/documentation/21-10-2022
- delete: dist/documentation/21-10-2022/mario-lylat-system.MOV
- delete: dist/documentation/21-10-2022/killer-instinct-matte.MOV
- delete: dist/documentation/21-10-2022/checkers.jpg
error: Uncaught (in promise) NotFound: No such file or directory (os error 2), remove 'dist/.git/index.lock'
    await Deno.remove(this.str, options)
    ^
    at async Object.remove (deno:runtime/js/30_fs.js:167:5)
    at async Path.rm (https://deno.land/x/wvvw@0.0.5/src/Core/Path.ts:155:5)
    at async SyncFiles.#deleteFile (https://deno.land/x/wvvw@0.0.5/src/App/File/Services/SyncFiles.ts:72:5)
    at async https://deno.land/x/wvvw@0.0.5/src/App/File/Services/SyncFiles.ts:35:9
    at async Promise.all (index 1)
    at async EventBus.send (https://deno.land/x/wvvw@0.0.5/src/Core/Events.ts:39:5)
```

**Comment by iatenothingbutriceforthreedays** [comment]
(`.git/` is in .gitignore)

**Comment by tycobbb** [comment]
is `dist` in `.gitignore` (if you don't want it in the repo) or `.wwwignore` (if you do)? the tool should probably ignore the build dir by default, even if it's not in either of those files.

**Comment by iatenothingbutriceforthreedays** [comment]
yes

**Comment by tycobbb** [comment]
weird. there's definitely a bug, that has existed since [the forest](https://github.com/frogfrogforg/c0llage), where deleting a file produced sometimes produced an error like this. never figured out why. if it's blocking u we can get on a discord call tho.

**Comment by tycobbb** [comment]
is your repo up on gh?

**Comment by tycobbb** [comment]
should probably be fixed by #a792ea & #8a7e0e
